[package]
name = "acelus-cas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tokio.workspace = true
blake3.workspace = true
reflink-copy = "0.1"
hex.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
blake3.workspace = true
